- name: Adding SSH keys to system/s
  blockinfile:
    path: ~/.ssh/authorized_keys
    block: |
      fsdfsdf
      dddd

- name: Restart service ssh
  become: true
  service:
    name: ssh
    state: restarted