- hosts : base
  gather_facts: no
  remote_user: root
  become: yes
  vars:
    ansible_ssh_private_key_file: "/home/kali/.ssh/id_rsa"
    ansible_python_interpreter: "/usr/bin/python3"
  roles :
  - {role: update}